DEMO_USERS = [
    {
        "id": "u-001",
        "name": "Admin User",
        "email": "admin@company.com",
        "department": "IT",
        "user_type": "employee",          # employee | contractor | service
        "is_active": True,
        "mfa_enabled": True,
        "last_login_days": 1,
        "roles": ["Admin", "HR-Read"],
        "groups": ["IT-Admins"],
    },
    {
        "id": "u-002",
        "name": "Employee User",
        "email": "employee@company.com",
        "department": "Operations",
        "user_type": "employee",
        "is_active": True,
        "mfa_enabled": False,
        "last_login_days": 9,
        "roles": ["Employee"],
        "groups": ["All-Employees"],
    },
    {
        "id": "u-003",
        "name": "Contractor A",
        "email": "contractor_a@vendor.com",
        "department": "Engineering",
        "user_type": "contractor",
        "is_active": True,
        "mfa_enabled": True,
        "last_login_days": 3,
        "roles": ["Admin"],               # risky
        "groups": ["Vendors"],
    },
    {
        "id": "u-004",
        "name": "Dormant User",
        "email": "dormant@company.com",
        "department": "Finance",
        "user_type": "employee",
        "is_active": True,
        "mfa_enabled": True,
        "last_login_days": 160,           # risky
        "roles": ["Finance-Read"],
        "groups": ["Finance"],
    },
    {
        "id": "u-005",
        "name": "Shared Inbox",
        "email": "shared-inbox@company.com",
        "department": "Support",
        "user_type": "service",
        "is_active": True,
        "mfa_enabled": False,
        "last_login_days": 2,
        "roles": ["Support-Write"],
        "groups": ["Support"],
    },
]
